### ISSUE TITLE
Unable To Save MKV File (HEVC) >4GB Despite "64 bits chunk offset" Checked.

### ISSUE THREAD

**Issue by MikNolhan** [juice/subler#1]
"The file is bigger than 4 GB, but it was created with 32bit data chunk offset.
Select 64bit data chunk offset in the save panel."

File is MKV Wrapper
hevc encoding
4.99GB
Contains 6 Chapters.

Environment Mac OS X Sonoma.

This even occurs with
`sudo open -a /Applications/Subler.app`

I have saved larger files prior with previous OS X versions and not had a problem. I am going to troubleshoot further as well.

**Comment by TransRapid** [comment]
I have saved larger files prior with previous OS X versions and not had a problem. I am going to troubleshoot further as well.

**Comment by TransRapid** [comment]
Issue was due to lack of free space, but error does not report correctly. I just saw that the larger files had caused a significant drop in space. The clue was when I saw it was giving me a permissions error even with sudo launch.

**Comment by MikNolhan** [comment]
Issue was due to lack of free space, but error does not report correctly. I just saw that the larger files had caused a significant drop in space. The clue was when I saw it was giving me a permissions error even with sudo launch.
